"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var express = require("express");
var health_routes_1 = require("./health.routes");
var company_routes_1 = require("./company.routes");
var product_routes_1 = require("./product.routes");
var review_routes_1 = require("./review.routes");
var widget_routes_1 = require("./widget.routes");
var router = express.Router();
exports.router = router;
router.use("/health", health_routes_1.healthRouter);
router.use("/companies", company_routes_1.default);
router.use("/products", product_routes_1.default);
router.use("/reviews", review_routes_1.default);
router.use("/widget", widget_routes_1.default);
